### ISSUE TITLE
Encode uri strings

### ISSUE THREAD

**Issue by jose-bail** [emersonbottero/ServiceNow.Core#11]
Characters, such as , &, etc. should be encoded to be used in the request url

One way is to use the Uri.EscapeDataString method

**Comment by emersonbottero** [comment]
didn't worked as expected
 Expected UserTable.RequestUrl "https://someUrl.com/api/now//table/sys_user?sysparm_fields=strange_name,age,sys_id&sysparm_limit=10000&sysparm_query%3DORDERBYage%5EORDERBYDESCstrange_name&sysparm_exclude_reference_link=true" to contain "https://someUrl.com/api/now//table/sys_user?sysparm_fields=strange_name,age,sys_id&sysparm_limit=10000&sysparm_query=ORDERBYage^ORDERBYDESCstrange_name".


 Expected UserTable.RequestUrl "https://someUrl.com/api/now//table/sys_user?sysparm_fields=name,age,sys_id&sysparm_limit=10000&sysparm_query%3Dname%2520INSTANCEOF%2520snow_table_name%2520%255E%2520age%2521%253D10%255EnameLikeBottero&sysparm_exclude_reference_link=true" to contain "https://someUrl.com/api/now//table/sys_user?sysparm_fields=name,age,sys_id&sysparm_limit=10000&sysparm_query=name INSTANCEOF snow_table_name ^ age!=10^nameLikeBottero&sysparm_exclude_reference_link=true".
